name: Install mdbook-pandoc system dependencies
runs:
  using: composite
  steps:
    - name: Install mdbook-pandoc dependencies
      uses: ./.github/workflows/apt-get-install
      with:
        packages: >
          fonts-noto
          fonts-noto-cjk
          fonts-noto-color-emoji
          fonts-noto-extra
          fonts-symbola
          librsvg2-bin
          texlive
          texlive-fonts-recommended
          texlive-lang-arabic
          texlive-lang-cjk
          texlive-lang-japanese
          texlive-luatex
