name: Install mdbook and dependencies

description: Install mdbook with the dependencies we need.

runs:
  using: composite
  steps:
    - name: Ensure cargo-binstall is installed
      uses: cargo-bins/cargo-binstall@main

    - name: Install mdbook-pandoc dependencies
      uses: ./.github/workflows/apt-get-install
      with:
        packages: >
          fonts-noto
          fonts-noto-cjk
          fonts-noto-color-emoji
          fonts-noto-extra
          fonts-symbola
          librsvg2-bin
          texlive
          texlive-fonts-recommended
          texlive-lang-arabic
          texlive-lang-cjk
          texlive-lang-japanese
          texlive-luatex
