name: Publish

on:
  push:
# TODO: for testing in my own fork.
#    branches:
#      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: pages
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  translations:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust cache
        uses: ./.github/workflows/setup-rust-cache

      - name: Install mdbook
        uses: ./.github/workflows/install-mdbook

      - name: Build course in English
        run: mdbook build -d book/en

      - name: Build course with all translations
        run: |
          for po_file in po/*.po; do
              MDBOOK_BOOK__LANGUAGE=${po_file:3:-3} \
              MDBOOK_PREPROCESSOR__GETTEXT__PO_FILE=$po_file \
              mdbook build -d book/${po_file:3:-3}

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: book

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
